[ccxt]
deribit.markets = ['^BTC\/USD:BTC$','^ETH\/USD:ETH$', '^BTC\/USD:BTC-\d{6}:\d*:[CP]$', '^ETH\/USD:ETH-\d{6}:\d*:[CP]$']

[database]
user = 'admin'
password = 'quest'
host = '127.0.0.1'
port = 8812
database = 'qdb'

[logging]
filename = '.\\app.log'
level = 'INFO'
