[ccxt]
# Windows
#deribit.markets = ['^BTC\/USD:BTC$','^ETH\/USD:ETH$', '^BTC\/USD:BTC-\d{6}:\d*:[CP]$', '^ETH\/USD:ETH-\d{6}:\d*:[CP]$']
# Posix
#deribit.markets = ['^BTC\/USD:BTC$','^ETH\/USD:ETH$', '^BTC\/USD:BTC-\d{6}-\d*-[CP]$', '^ETH\/USD:ETH-\d{6}-\d*-[CP]$']
#deribit.markets = ['^BTC\/USD:BTC$','^ETH\/USD:ETH$', ]
#binance.markets = ['^BTC\/USD:BTC$','^ETH\/USD:ETH$', ]
exchanges = ['deribit', 'binance',]

[database]
user = 'admin'
password = 'quest'
host = '127.0.0.1'
port = 8812
database = 'qdb'

[logging]
# Windows
#filename = '.\\app.log'
# Posix
filename = './app.log'
level = 'INFO'
